# Generated by Django 5.1 on 2024-09-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_event_date_alter_event_event_name_finance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
