# Generated by Django 5.1 on 2024-09-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
