# Generated by Django 5.1 on 2024-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_finance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='mode',
            field=models.CharField(max_length=50),
        ),
    ]
