# Generated by Django 5.1 on 2024-09-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_finance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_amount',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
