# Generated by Django 5.1 on 2024-10-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_event_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
    ]
